apiVersion: v1
kind: ConfigMap
metadata:
  name: titanic-api-config
data:
  FLASK_ENV: production
  FLASK_DEBUG: "false"
  GUNICORN_WORKERS: "4"
  GUNICORN_WORKER_CLASS: "sync"
  GUNICORN_TIMEOUT: "60"
  GUNICORN_KEEPALIVE: "5"
  GUNICORN_ACCESS_LOG_FORMAT: '%({X-Forwarded-For}i)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %(D)s'
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "10"
  DATABASE_POOL_TIMEOUT: "30"
  DATABASE_POOL_RECYCLE: "3600"
  LOG_LEVEL: "INFO"
