apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: titanic-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: titanic-api
  unhealthyPodEvictionPolicy: AlwaysAllow
