apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titanic-api-ingress
  namespace: titanic-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: titanic-api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: titanic-api-service
            port:
              number: 5000