apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: titanic-api

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc-postgres.yaml
  - statefulset-postgres.yaml
  - service-postgres.yaml
  - deployment-app.yaml
  - service-clusterip.yaml
  - service-loadbalancer.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy-db.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - serviceaccount-rolebinding.yaml

images:
  - name: titanic-api
    newTag: latest

commonLabels:
  app: titanic-api