apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: pipeops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: pipeops
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myapp-secret-reader-binding
  namespace: pipeops
subjects:
  - kind: ServiceAccount
    name: myapp-sa
    namespace: pipeops
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
