apiVersion: v1
kind: Service
metadata:
  name: titanic-api-lb
  namespace: titanic-api
  labels:
    app: titanic-api
spec:
  selector:
    app: titanic-api
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer