apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ default "" .Values.postgres.password | b64enc }}
  DATABASE_URL: {{ default "" .Values.postgres.databaseUrl | b64enc }}
