apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "myapp.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "myapp.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
