apiVersion: v1
kind: ServiceAccount
metadata:
  name: titanic-api-sa
  namespace: titanic-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: titanic-api-role
  namespace: titanic-api
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: titanic-api-rolebinding
  namespace: titanic-api
subjects:
- kind: ServiceAccount
  name: titanic-api-sa
  namespace: titanic-api
roleRef:
  kind: Role
  name: titanic-api-role
  apiGroup: rbac.authorization.k8s.io
